version: '3'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=shared-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_N8N_PASSWORD} # Change this to a secure password
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${ADMIN_PASSWORD}  # Change this to a secure password
      - N8N_SECURE_COOKIE=false
    volumes:
      - ${DOCKER_VOLUME_PATH}/n8n_data:/home/node/.n8n
    networks:
      - shared_network

volumes:
  n8n_data:
    name: n8n_data

networks:
  shared_network:
    external: true
    name: shared_network